# Generated by Django 3.0.3 on 2020-02-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('car_model', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('transmission', models.SmallIntegerField(choices=[(1, 'Механика'), (2, 'Автомат'), (3, 'Робот')], verbose_name='Коробка передач')),
                ('color', models.CharField(max_length=30)),
            ],
        ),
    ]
